In [1]:
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import tensorflow_datasets as tfds

### Checking stratification
Validation set:

In [5]:
ds = tfds.load('malaria', 
               split=('train[60%:80%]'), 
               shuffle_files=True,
              data_dir='./data',
               batch_size=-1,
              download=False,
              as_supervised=True,
              with_info=False)
ds

2023-01-27 11:25:16.912640: W tensorflow/tsl/framework/cpu_allocator_impl.cc:82] Allocation of 1591301250 exceeds 10% of free system memory.


(<tf.Tensor: shape=(5511, 385, 250, 3), dtype=uint8, numpy=
 array([[[[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],
 
         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],
 
         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],
 
         ...,
 
         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],
 
         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],
 
         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]],
 
 
        [[[0, 0, 0],
          [0, 0, 0],
          [0, 0

In [8]:
np.unique(ds[1].numpy(), return_counts=True)

(array([0, 1]), array([2757, 2754]))

Test set:

In [9]:
ds = tfds.load('malaria', 
               split=('train[80%:]'), 
               shuffle_files=True,
              data_dir='./data',
               batch_size=-1,
              download=False,
              as_supervised=True,
              with_info=False)
ds

2023-01-27 11:27:28.469803: W tensorflow/tsl/framework/cpu_allocator_impl.cc:82] Allocation of 983892000 exceeds 10% of free system memory.


(<tf.Tensor: shape=(5512, 238, 250, 3), dtype=uint8, numpy=
 array([[[[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],
 
         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],
 
         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],
 
         ...,
 
         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],
 
         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],
 
         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]],
 
 
        [[[0, 0, 0],
          [0, 0, 0],
          [0, 0

In [10]:
np.unique(ds[1].numpy(), return_counts=True)

(array([0, 1]), array([2780, 2732]))

### Largest image size
Images have different sizes.
I cannot load the whole dataset or even 60% of it due to memory shortage, so I have to use a loop.

In [28]:
ds = tfds.load('malaria', 
               split='train', 
               shuffle_files=False,
              data_dir='./data',
               batch_size=1,
              download=False,
              as_supervised=True,
              with_info=False)
print(ds)

<PrefetchDataset element_spec=(TensorSpec(shape=(None, None, None, 3), dtype=tf.uint8, name=None), TensorSpec(shape=(None,), dtype=tf.int64, name=None))>


In [31]:
max1 = 0
max2 = 0
for image, label in ds:
    if image.shape[1] > max1:
        max1 = image.shape[1]
    if image.shape[2] > max2:
        max2 = image.shape[2]
print(max1, max2)

385 394
